<?php

namespace Database\Seeders;

use App\Models\Appointment;
use App\Models\Doctor;
use App\Models\Examination;
use App\Models\Invoice;
use App\Models\Medicine;
use App\Models\Patient;
use App\Models\Payment;
use App\Models\Prescription;
use App\Models\PrescriptionItem;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DemoFlowSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::transaction(function () {
            $doctorUser = User::where('email', 'doctor@clinic.test')
                ->firstOrFail();

            $doctor = Doctor::where('user_id', $doctorUser->id)
                ->firstOrFail();

            $patient = Patient::where('code', 'PAT-0001')
                ->firstOrFail();

            $paracetamol = Medicine::where('code', 'MED-0001')
                ->firstOrFail();

            $amoxicillin = Medicine::where('code', 'MED-0002')
                ->firstOrFail();

            $appointment = Appointment::updateOrCreate(
                [
                    'doctor_id' => $doctor->id,
                    'patient_id' => $patient->id,
                    'reason' => 'Demo clinic examination flow',
                ],
                [
                    'scheduled_at' => now()
                        ->subDay()
                        ->setTime(9, 0),
                    'status' => 'completed',
                ]
            );

            $examination = Examination::updateOrCreate(
                [
                    'appointment_id' => $appointment->id,
                ],
                [
                    'doctor_id' => $doctor->id,
                    'patient_id' => $patient->id,
                    'diagnosis' => 'Acute upper respiratory infection',
                    'notes' => 'Demo examination generated by T3.17 seeder.',
                    'examined_at' => $appointment->scheduled_at,
                ]
            );

            $prescription = Prescription::updateOrCreate(
                [
                    'examination_id' => $examination->id,
                ],
                [
                    'doctor_id' => $doctor->id,
                    'notes' => 'Demo prescription for the complete clinic flow.',
                ]
            );

            $this->createPrescriptionItem(
                prescription: $prescription,
                medicine: $paracetamol,
                quantity: 2,
                dosage: '500mg',
                usageInstruction: 'Take 1 tablet twice daily after meals.'
            );

            $this->createPrescriptionItem(
                prescription: $prescription,
                medicine: $amoxicillin,
                quantity: 1,
                dosage: '500mg',
                usageInstruction: 'Take 1 capsule three times daily after meals.'
            );

            $paracetamol->refresh();
            $amoxicillin->refresh();

            $medicineTotal =
               (2 * (float) $paracetamol->price)
               + (1 * (float) $amoxicillin->price);

            $examinationFee = (float) config(
                'clinic.examination_fee',
                100000
            );

            $subtotal = $examinationFee + $medicineTotal;
            $discount = 0;
            $total = $subtotal - $discount;

            $invoice = Invoice::updateOrCreate(
                [
                    'examination_id' => $examination->id,
                ],
                [
                    'invoice_code' => 'DEMO-INV-0001',
                    'subtotal' => $subtotal,
                    'discount' => $discount,
                    'total' => $total,
                    'status' => 'paid',
                    'issued_at' => now()->subDay()->setTime(10, 0),
                ]
            );

            Payment::updateOrCreate(
                [
                    'provider_order_id' => 'DEMO-PAYPAL-ORDER-0001',
                ],
                [
                    'invoice_id' => $invoice->id,
                    'amount' => $invoice->total,
                    'method' => 'paypal',
                    'status' => 'completed',
                    'provider' => 'paypal',
                    'provider_capture_id' => 'DEMO-PAYPAL-CAPTURE-0001',
                    'paid_at' => now()->subDay()->setTime(10, 5),
                    'note' => 'Demo completed PayPal payment generated by T3.17.',
                ]
            );
        });
    }

    private function createPrescriptionItem(
        Prescription $prescription,
        Medicine $medicine,
        int $quantity,
        string $dosage,
        string $usageInstruction
    ): void {
        $item = PrescriptionItem::firstOrCreate(
            [
                'prescription_id' => $prescription->id,
                'medicine_id' => $medicine->id,
            ],
            [
                'quantity' => $quantity,
                'dosage' => $dosage,
                'usage_instruction' => $usageInstruction,
            ]
        );

        if (! $item->wasRecentlyCreated) {
            return;
        }

        if ($medicine->stock < $quantity) {
            throw new \RuntimeException(
                "Not enough stock for demo medicine: {$medicine->code}"
            );
        }

        $medicine->decrement('stock', $quantity);
    }
}
